#ifndef DEFINES_H_
#define DEFINES_H_

#define FILE_CONTENT_INIT_CAPACITY 10
#define LINE_INIT_CAPACITY 20
#define SIZE_INIT_VALUE 0
#define INCREASE_VALUE 2
#define CAPACITY_COMPARE_VALUE 1

#endif // DEFINES_H_